import streamlit as st
import time

from components.custom_audio_player import custom_audio_player
from utils import fetch_random_music, submit_rating, load_css


st.set_page_config(initial_sidebar_state='collapsed', page_icon=':musical_note:')
load_css()

if 'random_track' not in st.session_state:
    track_data, error = fetch_random_music()
    if error:
        st.error(error)
        st.stop()
    else:
        st.session_state.random_track = track_data

custom_audio_player(st.session_state.random_track['file'])

st.markdown('<p style="font-size: 20px;">Do you think this track was generated by AI?</p>', unsafe_allow_html=True)
rating = st.select_slider('Use the slider to rate from 1 (Definitely AI) to 5 (Definitely Human)',
                          options=[1, 2, 3, 4, 5], value=3)

rating_labels = {
    1: 'Definitely AI',
    2: 'Probably AI',
    3: 'Unsure',
    4: 'Probably Human',
    5: 'Definitely Human'
}

st.write(f'Your rating: {rating} - {rating_labels[rating]}')

if st.button('Submit Rating', type='primary'):
    result, error = submit_rating(st.session_state.random_track['id'], rating)
    if error:
        st.error(error)
    else:
        st.success('Rating submitted successfully!')
        st.info('Up next: Moving to the next track...')
        time.sleep(1)
        track_data, error = fetch_random_music()
        if error:
            st.error(error)
        else:
            st.session_state.random_track = track_data
            st.rerun()

if st.button('Skip to Next Song'):
    track_data, error = fetch_random_music()
    if error:
        st.error(error)
    else:
        st.session_state.random_track = track_data
        st.rerun()
