import requests
import streamlit as st
import time

from components.custom_audio_player import custom_audio_player
from utils import fetch_random_music, submit_rating, load_css


st.set_page_config(initial_sidebar_state='collapsed')
load_css()

if 'random_track' not in st.session_state:
    st.session_state.random_track = fetch_random_music()

custom_audio_player(st.session_state.random_track['file'])

st.markdown('<p style="font-size: 20px;">Do you think this track was generated by AI?</p>', unsafe_allow_html=True)
rating = st.select_slider('Use the slider to rate from 1 (Definitely AI) to 5 (Definitely Human)',
                          options=[1, 2, 3, 4, 5], value=3)

rating_labels = {
    1: 'Definitely AI',
    2: 'Probably AI',
    3: 'Unsure',
    4: 'Probably Human',
    5: 'Definitely Human'
}

st.write(f'Your rating: {rating} - {rating_labels[rating]}')

if st.button('Submit Rating', type='primary'):
    try:
        result = submit_rating(st.session_state.random_track['id'], rating)
        st.success('Rating submitted successfully!')
        st.info('Up next: Moving to the next track...')
        time.sleep(1)
        st.session_state.random_track = fetch_random_music()
        st.rerun()
    except requests.HTTPError as e:
        error_data = e.response.json()
        st.error(error_data.get('error', 'Server error. Please try again.'))
        if e.response.status_code == 404:
            time.sleep(1)
            st.session_state.random_track = fetch_random_music()
            st.rerun()

if st.button('Skip to Next Song'):
    st.session_state.random_track = fetch_random_music()
    st.rerun()
