import requests
import streamlit as st
import time

from components.custom_audio_player import custom_audio_player
from utils import fetch_random_music, submit_rating, load_css


st.set_page_config(layout='wide', initial_sidebar_state='collapsed')
load_css()

if 'random_track' not in st.session_state:
    st.session_state.random_track = fetch_random_music()

custom_audio_player(st.session_state.random_track['file'])

# Rating section
st.write('Do you think this music was generated by AI?')
rating = st.slider('Rate from 1 (Definitely AI) to 5 (Definitely Human)', 1, 5, 3)

rating_labels = {
    1: 'Definitely AI',
    2: 'Probably AI',
    3: 'Unsure',
    4: 'Probably Human',
    5: 'Definitely Human'
}

st.write(f'Your rating: {rating} - {rating_labels[rating]}')

if st.button('Submit Rating'):
    try:
        result = submit_rating(st.session_state.random_track['id'], rating)
        st.success('Rating submitted successfully!')

        time.sleep(1)
        st.session_state.random_track = fetch_random_music()
        st.rerun()
    except requests.RequestException as e:
        st.error(f'Error submitting rating: {str(e)}')

if st.button('Skip to Next Song'):
    st.session_state.random_track = fetch_random_music()
    st.rerun()
