# Generated by Django 5.1 on 2024-10-17 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(choices=[('classical', 'Classical'), ('pop', 'Pop'), ('exp1', 'trained with pop'), ('exp2', 'trained with pop and classical'), ('exp3', 'trained with pop and classical(CnG major)')], max_length=50)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('key', models.CharField(blank=True, max_length=3, null=True)),
                ('npvi', models.FloatField(blank=True, null=True)),
                ('note_density', models.FloatField(blank=True, null=True)),
                ('pitch_range', models.IntegerField(blank=True, null=True)),
                ('pitch_count', models.IntegerField(blank=True, null=True)),
                ('pitch_class_count', models.IntegerField(blank=True, null=True)),
                ('pitch_entropy', models.FloatField(blank=True, null=True)),
                ('pitch_class_entropy', models.FloatField(blank=True, null=True)),
                ('pitch_in_scale_rate', models.FloatField(blank=True, null=True)),
                ('scale_consistency', models.FloatField(blank=True, null=True)),
                ('polyphony', models.FloatField(blank=True, null=True)),
                ('polyphony_rate', models.FloatField(blank=True, null=True)),
                ('complexity', models.FloatField(blank=True, null=True)),
                ('originality', models.FloatField(blank=True, null=True)),
                ('gradus', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Music Track',
                'verbose_name_plural': 'Music Tracks',
                'constraints': [models.UniqueConstraint(fields=('title', 'label'), name='unique_music_title_label')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.music')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
