# Generated by Django 5.1 on 2024-10-20 22:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='iv_dist1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=25),
        ),
        migrations.AddField(
            model_name='music',
            name='iv_dist2',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=25), blank=True, null=True, size=25),
        ),
        migrations.AddField(
            model_name='music',
            name='ivdir_dist1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=12),
        ),
        migrations.AddField(
            model_name='music',
            name='ivsize_dist1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=13),
        ),
        migrations.AddField(
            model_name='music',
            name='pc_dist1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=12),
        ),
        migrations.AddField(
            model_name='music',
            name='pc_dist2',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=12), blank=True, null=True, size=12),
        ),
    ]
