name: Quality Assurance

on:
  push:
    branches: [master]
  pull_request:
    branches: [production]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r frontend/requirements.txt
        pip install coverage pytest

    - name: Lint
      run: |
        pip install flake8
        flake8 backend frontend

    - name: Backend test
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        DJANGO_SETTINGS_MODULE: core.settings
        SECRET_KEY: test_key
        DEBUG: True
      run: |
        pip install coverage
        cd backend/
        coverage run manage.py test
        coverage report

    - name: Frontend test
      run: |
        cd frontend/
        pytest tests.py
